#gt915 touchpanel driver

obj-$(CONFIG_TOUCHSCREEN_GT9XX_DRIVER_V22)	+= gt9xx.o
#gt915 update file
obj-$(CONFIG_GT9XX_TOUCHPANEL_UPDATE_V22)	+= gt9xx_update.o
#debug tool
obj-$(CONFIG_GT9XX_TOUCHPANEL_DEBUG_V22)	+= goodix_tool.o
